const GAMER_CONTEXT_ACTION_TYPES = {
  UPDATE_AGE: "UPDATE_AGE",
  UPDATE_AVATAR: "UPDATE_AVATAR",
  UPDATE_STATUS: "UPDATE_STATUS",
  UPDATE_USERNAME: "UPDATE_USERNAME",
};

export { GAMER_CONTEXT_ACTION_TYPES };
