export const RANDOM_IMAGE_ACTION_TYPES = {
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
  UPDATE_WIDTH: "UPDATE_WIDTH",
  UPDATE_HEIGHT: "UPDATE_HEIGHT",
};
